[build]
command = "pip install -r requirements.txt"
publish = "."
functions = "functions"

[[redirects]]
from = "/*"
to = "/templates/index.html"
status = 200

[build.environment]
PYTHON_VERSION = "3.8" 